-- No-op.
-- `checkoutButtonText` is introduced by the later
-- 20260104100000_add_style_checkout_button_text migration. This migration
-- previously tried to modify that column before it existed, which caused
-- Prisma P3018 / MySQL 1054 on databases applying the history in order.
