CREATE TABLE `addtocartbarsettings` (
  `id`                            INT NOT NULL AUTO_INCREMENT,
  `shop`                          VARCHAR(255) NOT NULL,
  `status`                        VARCHAR(20) NOT NULL DEFAULT 'active',

  `mobileShowCondition`           VARCHAR(64) NOT NULL DEFAULT 'scrollDown',
  `mobileScrollDepth`             INT NOT NULL DEFAULT 380,
  `mobileStickyPosition`          VARCHAR(16) NOT NULL DEFAULT 'bottom',
  `mobileCtaAnimation`            VARCHAR(32) NOT NULL DEFAULT 'pulse',
  `mobileBgColor`                 VARCHAR(32) NULL,
  `mobileTextColor`               VARCHAR(32) NULL,
  `mobileCtaBgColor`              VARCHAR(32) NULL,
  `mobileCtaTextColor`            VARCHAR(32) NULL,
  `mobileImageOutlineColor`       VARCHAR(32) NULL,
  `mobileShowProductImage`        BOOLEAN NOT NULL DEFAULT TRUE,
  `mobileShowProductTitle`        BOOLEAN NOT NULL DEFAULT TRUE,
  `mobileShowPrice`               BOOLEAN NOT NULL DEFAULT TRUE,
  `mobileShowCompareAtPrice`      BOOLEAN NOT NULL DEFAULT TRUE,
  `mobileShowQuantity`            BOOLEAN NOT NULL DEFAULT TRUE,
  `mobileShowVariantSelector`     BOOLEAN NOT NULL DEFAULT TRUE,
  `mobileShowVariantLabel`        BOOLEAN NOT NULL DEFAULT TRUE,
  `mobileShowPriceOnCta`          BOOLEAN NOT NULL DEFAULT TRUE,
  `mobileShowCompareAtPriceOnCta` BOOLEAN NOT NULL DEFAULT TRUE,

  `desktopShowCondition`           VARCHAR(64) NOT NULL DEFAULT 'scrollDown',
  `desktopScrollDepth`             INT NOT NULL DEFAULT 380,
  `desktopStickyPosition`          VARCHAR(16) NOT NULL DEFAULT 'bottom',
  `desktopCtaAnimation`            VARCHAR(32) NOT NULL DEFAULT 'pulse',
  `desktopBgColor`                 VARCHAR(32) NULL,
  `desktopTextColor`               VARCHAR(32) NULL,
  `desktopCtaBgColor`              VARCHAR(32) NULL,
  `desktopCtaTextColor`            VARCHAR(32) NULL,
  `desktopImageOutlineColor`       VARCHAR(32) NULL,
  `desktopShowProductImage`        BOOLEAN NOT NULL DEFAULT TRUE,
  `desktopShowProductTitle`        BOOLEAN NOT NULL DEFAULT TRUE,
  `desktopShowPrice`               BOOLEAN NOT NULL DEFAULT TRUE,
  `desktopShowCompareAtPrice`      BOOLEAN NOT NULL DEFAULT TRUE,
  `desktopShowQuantity`            BOOLEAN NOT NULL DEFAULT TRUE,
  `desktopShowVariantSelector`     BOOLEAN NOT NULL DEFAULT TRUE,
  `desktopShowVariantLabel`        BOOLEAN NOT NULL DEFAULT TRUE,
  `desktopShowPriceOnCta`          BOOLEAN NOT NULL DEFAULT TRUE,
  `desktopShowCompareAtPriceOnCta` BOOLEAN NOT NULL DEFAULT TRUE,

  `ctaBehavior`                   VARCHAR(32) NOT NULL DEFAULT 'addToCart',
  `afterAddToCart`                VARCHAR(64) NOT NULL DEFAULT 'openCartWidget',
  `homepageProductId`             VARCHAR(255) NULL,
  `homepageProductTitle`          VARCHAR(255) NULL,
  `customCss`                     LONGTEXT NULL,
  `customJs`                      LONGTEXT NULL,
  `desktopZIndex`                 INT NOT NULL DEFAULT 5000,
  `mobileZIndex`                  INT NOT NULL DEFAULT 5000,

  `createdAt`                     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt`                     DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `addtocartbarsettings_shop_key` (`shop`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
